project website: https://www.kaggle.com/competitions/costa-rican-household-poverty-prediction/overview

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df

,Id,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,...,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq,Target
0,ID_279628684,190000.0,0,3,0,1,1,0,NaN,0,...,100,1849,1,100,0,1.000000,0.0000,100.0000,1849,4
1,ID_f29eb3ddd,135000.0,0,4,0,1,1,1,1.0,0,...,144,4489,1,144,0,1.000000,64.0000,144.0000,4489,4
2,ID_68de51c94,NaN,0,8,0,1,1,0,NaN,0,...,121,8464,1,0,0,0.250000,64.0000,121.0000,8464,4
3,ID_d671db89c,180000.0,0,5,0,1,1,1,1.0,0,...,81,289,16,121,4,1.777778,1.0000,121.0000,289,4
4,ID_d56d6f5f5,180000.0,0,5,0,1,1,1,1.0,0,...,121,1369,16,121,4,1.777778,1.0000,121.0000,1369,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9552,ID_d45ae367d,80000.0,0,6,0,1,1,0,NaN,0,...,81,2116,25,81,1,1.562500,0.0625,68.0625,2116,2
9553,ID_c94744e07,80000.0,0,6,0,1,1,0,NaN,0,...,0,4,25,81,1,1.562500,0.0625,68.0625,4,2
9554,ID_85fc658f8,80000.0,0,6,0,1,1,0,NaN,0,...,25,2500,25,81,1,1.562500,0.0625,68.0625,2500,2
9555,ID_ced540c61,80000.0,0,6,0,1,1,0,NaN,0,...,121,676,25,81,1,1.562500,0.0625,68.0625,676,2
9556,ID_a38c64491,80000.0,0,6,0,1,1,0,NaN,0,...,64,441,25,81,1,1.562500,0.0625,68.0625,441,2

In [4]:
# Loop through columns and attempt to convert to numeric types
for column in df.columns:
    try:
        df[column] = pd.to_numeric(df[column], errors='coerce').astype(float)
    except ValueError:
        # If the conversion fails, leave the column as is
        pass

In [5]:
df.isnull().sum().sort_values(ascending=False)

Id                 9557
idhogar            9368
rez_esc            7928
v18q1              7342
v2a1               6860
                   ...
abastaguadentro       0
cielorazo             0
techootro             0
techocane             0
Target                0
Length: 143, dtype: int64

In [6]:
df.drop(['rez_esc','v18q1','v2a1'], axis=1, inplace =True)

In [7]:
df.isnull().sum().sort_values(ascending=False)

Id                 9557
idhogar            9368
edjefa             6299
dependency         3939
edjefe             3885
                   ...
abastaguafuera        0
abastaguadentro       0
cielorazo             0
techootro             0
Target                0
Length: 140, dtype: int64

In [8]:
df = df.fillna(0)

In [9]:
df.isnull().sum().sort_values(ascending=False)

Id                 0
hogar_total        0
parentesco11       0
parentesco12       0
idhogar            0
                  ..
abastaguafuera     0
abastaguadentro    0
cielorazo          0
techootro          0
Target             0
Length: 140, dtype: int64

In [10]:
for column, dtype in df.dtypes.items():
    print(f"{column}: {dtype}")

Id: float64
hacdor: float64
rooms: float64
hacapo: float64
v14a: float64
refrig: float64
v18q: float64
r4h1: float64
r4h2: float64
r4h3: float64
r4m1: float64
r4m2: float64
r4m3: float64
r4t1: float64
r4t2: float64
r4t3: float64
tamhog: float64
tamviv: float64
escolari: float64
hhsize: float64
paredblolad: float64
paredzocalo: float64
paredpreb: float64
pareddes: float64
paredmad: float64
paredzinc: float64
paredfibras: float64
paredother: float64
pisomoscer: float64
pisocemento: float64
pisoother: float64
pisonatur: float64
pisonotiene: float64
pisomadera: float64
techozinc: float64
techoentrepiso: float64
techocane: float64
techootro: float64
cielorazo: float64
abastaguadentro: float64
abastaguafuera: float64
abastaguano: float64
public: float64
planpri: float64
noelec: float64
coopele: float64
sanitario1: float64
sanitario2: float64
sanitario3: float64
sanitario5: float64
sanitario6: float64
energcocinar1: float64
energcocinar2: float64
energcocinar3: float64
energcocinar4: float64
elimbasu1: float64
elimbasu2: float64
elimbasu3: float64
elimbasu4: float64
elimbasu5: float64
elimbasu6: float64
epared1: float64
epared2: float64
epared3: float64
etecho1: float64
etecho2: float64
etecho3: float64
eviv1: float64
eviv2: float64
eviv3: float64
dis: float64
male: float64
female: float64
estadocivil1: float64
estadocivil2: float64
estadocivil3: float64
estadocivil4: float64
estadocivil5: float64
estadocivil6: float64
estadocivil7: float64
parentesco1: float64
parentesco2: float64
parentesco3: float64
parentesco4: float64
parentesco5: float64
parentesco6: float64
parentesco7: float64
parentesco8: float64
parentesco9: float64
parentesco10: float64
parentesco11: float64
parentesco12: float64
idhogar: float64
hogar_nin: float64
hogar_adul: float64
hogar_mayor: float64
hogar_total: float64
dependency: float64
edjefe: float64
edjefa: float64
meaneduc: float64
instlevel1: float64
instlevel2: float64
instlevel3: float64
instlevel4: float64
instlevel5: float64
instlevel6: float64
instlevel7: float64
instlevel8: float64
instlevel9: float64
bedrooms: float64
overcrowding: float64
tipovivi1: float64
tipovivi2: float64
tipovivi3: float64
tipovivi4: float64
tipovivi5: float64
computer: float64
television: float64
mobilephone: float64
qmobilephone: float64
lugar1: float64
lugar2: float64
lugar3: float64
lugar4: float64
lugar5: float64
lugar6: float64
area1: float64
area2: float64
age: float64
SQBescolari: float64
SQBage: float64
SQBhogar_total: float64
SQBedjefe: float64
SQBhogar_nin: float64
SQBovercrowding: float64
SQBdependency: float64
SQBmeaned: float64
agesq: float64
Target: float64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9557 entries, 0 to 9556
Columns: 140 entries, Id to Target
dtypes: float64(140)
memory usage: 10.2 MB

In [12]:
df['Target'].unique()

array([4., 2., 3., 1.])

In [13]:
df['Target'] = df['Target'].map({1: 0, 2: 1, 3: 2, 4: 3})

In [14]:
max_values = df.max()

# Sort the maximum values in descending order
max_values_descending = max_values.sort_values(ascending=False)

# Display the maximum values in descending order
print("Max values of each column in descending order:")
print(max_values_descending)

Max values of each column in descending order:
idhogar       2.690850e+93
SQBage        9.409000e+03
agesq         9.409000e+03
SQBmeaned     1.369000e+03
SQBedjefe     4.410000e+02
                  ...
sanitario6    1.000000e+00
sanitario5    1.000000e+00
sanitario3    1.000000e+00
elimbasu5     0.000000e+00
Id            0.000000e+00
Length: 140, dtype: float64

In [15]:
# Set the percentage threshold
percentage_threshold = 3

# Function to filter rows based on top percentage
def filter_top_percentage(df, column_name, percentage_threshold):
    threshold_value = df[column_name].quantile(1 - percentage_threshold / 100)
    return df[df[column_name] <= threshold_value]

# Iterate through each column and filter rows
for column in df.columns:
    df = filter_top_percentage(df, column, percentage_threshold)

In [16]:
#df_ = df_cleaned;
y = df['Target']
x = df.drop('Target', axis = 1, inplace = False)
x = pd.get_dummies(x, drop_first = True)

In [17]:
x.shape, y.shape

((4517, 139), (4517,))

In [18]:
df.isna().sum()

Id                 0
hacdor             0
rooms              0
hacapo             0
v14a               0
                  ..
SQBovercrowding    0
SQBdependency      0
SQBmeaned          0
agesq              0
Target             0
Length: 140, dtype: int64

In [21]:
def algo_test(x,y):
#def algo_test(x_train,x_test,y_train,y_test):
    
    import numpy as np

    from scipy import stats
    import matplotlib.pyplot as plt
    %matplotlib inline 
    import seaborn as sns

    from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
    from sklearn.linear_model import LinearRegression, ElasticNet, Ridge, Lasso
    from sklearn.tree import ExtraTreeClassifier
    from sklearn.ensemble import GradientBoostingRegressor
    from xgboost import XGBRegressor 

    from sklearn.model_selection import train_test_split

    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
    from sklearn.naive_bayes import GaussianNB
    from sklearn.naive_bayes import BernoulliNB
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.linear_model import LogisticRegression
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.ensemble import ExtraTreesClassifier
    from xgboost import XGBClassifier

    import warnings
    warnings.filterwarnings('ignore')
    #plt.style.use('')

    G = GaussianNB()
    B = BernoulliNB()
    K = KNeighborsClassifier()
    L = LogisticRegression()
    D = DecisionTreeClassifier()
    RF = RandomForestClassifier()
    ETC = ExtraTreesClassifier()
    XG = XGBClassifier()
    
    x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 13)
    
    algos = [G,B,L,D, RF, ETC, XG]
    #algos = [G,B,L, RF, ETC, XG]
    #algos = [G,B,L,D,  RF, ETC]
    
    #algo_names = [ "Gaussian", "Bernoulli", "K-Neighbors", "Logistic Regression", "Decision Tree", "Random Forest", "ExtraTreeClassifier" ]
    algo_names = [ "Gaussian", "Bernoulli","Logistic Regression", "Decision Tree", \
                  "Random Forest", "ExtraTreeClassifier","XGBClassifier" ]
    #algo_names = [ "Gaussian", "Bernoulli","Logistic Regression", \
    #              "Random Forest", "ExtraTreeClassifier","XGBClassifier" ]
    
    ASC = [];
    
    result =  result = pd.DataFrame(columns = ['Accuracy_Score'], index = algo_names)
    
    i = 0;
    
    for algo in algos :
        
        algo.fit(x_train,y_train)
        #print (accuracy_score(  y_test, algo.predict(x_test) ))
        ASC.append(  accuracy_score(  y_test, algo.predict(x_test) ) )
        
        print( "Confusion matrix: ",format(algo_names[i]) )
        i = i+1;
        print ( confusion_matrix(algo.predict(x_test),y_test) )
        #print (classification_report(y_test,algo.predict(x_test) ))
        
        #algo.fit(x,y)
        print (accuracy_score(  y, algo.predict(x) ))
        #ASC.append(  accuracy_score(  y, algo.predict(x) ) )
    
    result.Accuracy_Score = ASC;

    return result.sort_values('Accuracy_Score', ascending=False)

In [22]:
algo_test(x,y)

Confusion matrix:  Gaussian
[[ 20  25  24  53]
 [ 19  50  18  59]
 [  9  18  27  62]
 [ 15  30  48 427]]
0.5886650431702457
Confusion matrix:  Bernoulli
[[ 16  18  14  28]
 [ 26  46  29  62]
 [  4  14  15  45]
 [ 17  45  59 466]]
0.6059331414655745
Confusion matrix:  Logistic Regression
[[  0   0   0   0]
 [  2   5   3   4]
 [  0   0   0   0]
 [ 61 118 114 597]]
0.6623865397387647
Confusion matrix:  Decision Tree
[[ 46   4   1  12]
 [  7 102  11  23]
 [  2   4  81  24]
 [  8  13  24 542]]
0.9705556785477086
Confusion matrix:  Random Forest
[[ 41   0   0   0]
 [  4  93   7   6]
 [  1   0  61   0]
 [ 17  30  49 595]]
0.9747620101837503
Confusion matrix:  ExtraTreeClassifier
[[ 50   2   0   0]
 [  5 107   5   1]
 [  1   1  85   2]
 [  7  13  27 598]]
0.9858313039628072
Confusion matrix:  XGBClassifier
[[ 50   1   1   1]
 [  5 106   7   4]
 [  2   4  81   4]
 [  6  12  28 592]]
0.9831746734558335

                     Accuracy_Score
ExtraTreeClassifier        0.929204
XGBClassifier              0.917035
Random Forest              0.873894
Decision Tree              0.852876
Logistic Regression        0.665929
Bernoulli                  0.600664
Gaussian                   0.579646